### ISSUE TITLE
Does not cleanup /tmp files/directories

### ISSUE THREAD

**Issue by lichtin** [ops4j/org.ops4j.pax.tinybundles#2] opened 2014-04-17 14:26 UTC
I'm seeing zillions of directories in /tmp created by tinybundles:

drwxrwxr-x 2 jenkins jenkins     4096 Apr 17 16:06 1397743577079-0
drwxrwxr-x 2 jenkins jenkins     4096 Apr 17 16:06 1397743592071-0
drwxrwxr-x 2 jenkins jenkins     4096 Apr 17 16:06 1397743608375-0
drwxrwxr-x 2 jenkins jenkins     4096 Apr 17 16:07 1397743626923-0
drwxrwxr-x 2 jenkins jenkins     4096 Apr 17 16:07 1397743645283-0
drwxrwxr-x 2 jenkins jenkins     4096 Apr 17 16:07 1397743674099-0
drwxrwxr-x 2 jenkins jenkins     4096 Apr 17 16:08 1397743684633-0
drwxrwxr-x 2 jenkins jenkins     4096 Apr 17 16:08 1397743701748-0
drwxrwxr-x 2 jenkins jenkins     4096 Apr 17 16:08 1397743720358-0
drwxrwxr-x 2 jenkins jenkins     4096 Apr 17 16:09 1397743736407-0
drwxrwxr-x 2 jenkins jenkins     4096 Apr 17 16:09 1397743752519-0
drwxrwxr-x 2 jenkins jenkins     4096 Apr 17 16:09 1397743779232-0
drwxrwxr-x 2 jenkins jenkins     4096 Apr 17 16:09 1397743798249-0
drwxrwxr-x 2 jenkins jenkins     4096 Apr 17 16:10 1397743812079-0
drwxrwxr-x 2 jenkins jenkins     4096 Apr 17 16:10 1397743831976-0
drwxrwxr-x 2 jenkins jenkins     4096 Apr 17 16:11 1397743863333-0
drwxrwxr-x 2 jenkins jenkins     4096 Apr 17 16:11 1397743899382-0
drwxrwxr-x 2 jenkins jenkins     4096 Apr 17 16:12 1397743939093-0

**Comment by oliverlietz** [comment] 2023-08-24 19:20
Cannot reproduce. Maybe fixed in newer OPS4J Store dependency.

**Closed by oliverlietz** 2023-08-24 19:20 UTC
Labels: status: cannot reproduce
